#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK

import argh
from argh import arg
from myapp.util import redis, confirm, remove_account_by_nid,\
    remove_account_by_email, reset_secret_key

class ChoicesCompleter(object):
    def __init__(self, choices=[]):
        self.choices = choices
    def __call__(self, prefix, **kwargs):
        return (c for c in self.choices if c.startswith(prefix))

def flushdb():
    "Flush DB!"
    if confirm('All data will be deleted. Are you sure?', resp=False):
        redis.flushdb()
        print "Your DB has been flushed."

def get_allaccounts():
    emails = []
    account_cnt = redis.get('account_cnt')
    if account_cnt:
        account_cnt = int(account_cnt)
        for nid in range(1, account_cnt + 1):
            rd_account_email = 'account:%s:email' % nid
            email = redis.get(rd_account_email)
            if email:
                emails.append(email)
    return emails

def allaccounts():
    "Show all accounts"
    for a in get_allaccounts():
        print a

def email_completer(prefix, **kwargs):
    accounts = get_allaccounts()
    if len(prefix) > 0:
        return [a for a in accounts if a.startswith(prefix)]
    return accounts

@arg('-e', '--email', help='delete account by email', completer=email_completer)
@arg('-n', '--nid', type=int, help='delete account by nid')
def delaccount(email, nid):
    "Delete a account"
    if not email or nid:
        print 'please specify email or nid'
        return
    if email:
        remove_account_by_email(email)
    elif nid:
        remove_account_by_nid(email)

def resetkey():
    "Reset session secret key"
    reset_secret_key()

if __name__ == '__main__':
    argh.dispatch_commands([flushdb, allaccounts, delaccount, resetkey])

