#!/usr/bin/env python

import aaargh
from myapp.util import redis, confirm, remove_account_by_nid,\
    remove_account_by_email, reset_secret_key

app = aaargh.App(description="myapp admin script")

# Application level arguments


@app.cmd(help = 'flush DB!')
def flushdb():
    if confirm('All data will be deleted. Are you sure?', resp=False):
        redis.flushdb()
        print "Your DB has been flushed."

@app.cmd(help = "show all accounts")
def allaccounts():
    account_cnt = redis.get('account_cnt')
    if account_cnt:
        account_cnt = int(account_cnt)
        for nid in range(1, account_cnt + 1):
            rd_account_email = 'account:%s:email' % nid
            email = redis.get(rd_account_email)
            if email:
                print email
    else:
        print "no accounts."

@app.cmd(help = 'delete a account')
@app.cmd_arg('-e', '--email', help='delete account by email')
@app.cmd_arg('-n', '--nid', type=int, help='delete account by nid')
def delaccount(email, nid):
    if not email or nid:
        print 'please specify email or nid'
        return
    if email:
        remove_account_by_email(email)
    elif nid:
        remove_account_by_nid(email)

@app.cmd(help = 'reset session secret key')
def resetkey():
    reset_secret_key()

if __name__ == '__main__':
    app.run()

